### ISSUE TITLE
Does not compile on perl 5.44

### ISSUE THREAD

**Issue by mauke** [p5pclub/devel-quickcover#21]
See https://www.cpantesters.org/cpan/report/c7cfb496-70ff-11f1-b542-a7899a264e67.

```
"/home/mauke/tmp/perl-5.44.0-RC1/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- QuickCover.bs blib/arch/auto/Devel/QuickCover/QuickCover.bs 644
c-gcc -c  -I. -D_REENTRANT -D_GNU_SOURCE -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -Wall -std=c89 -D_XOPEN_SOURCE=700 -O2 -flto=auto -march=native   -DVERSION=\"0.900014\" -DXS_VERSION=\"0.900014\" -fPIC "-I/home/mauke/tmp/perl-5.44.0-RC1/lib/5.44.0/x86_64-linux-thread-multi/CORE"   cover.c
In file included from /home/mauke/tmp/perl-5.44.0-RC1/lib/5.44.0/x86_64-linux-thread-multi/CORE/perl.h:8004,
                 from util.h:10,
                 from cover.h:11,
                 from cover.c:10:
/home/mauke/tmp/perl-5.44.0-RC1/lib/5.44.0/x86_64-linux-thread-multi/CORE/inline.h: In function ‘Perl_cx_poploop’:
/home/mauke/tmp/perl-5.44.0-RC1/lib/5.44.0/x86_64-linux-thread-multi/CORE/inline.h:4357:9: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
 4357 |         for (SV **svp = cx->blk_loop.itervar_u.svp + 1; how_many; svp++, how_many--) {
      |         ^~~
/home/mauke/tmp/perl-5.44.0-RC1/lib/5.44.0/x86_64-linux-thread-multi/CORE/inline.h:4357:9: note: use option ‘-std=c99’, ‘-std=gnu99’, ‘-std=c11’ or ‘-std=gnu11’ to compile your code
/home/mauke/tmp/perl-5.44.0-RC1/lib/5.44.0/x86_64-linux-thread-multi/CORE/inline.h:4374:9: error: C++ style comments are not allowed in ISO C90
 4374 |         // LV ref around a package lexical, mg_obj gives its GV
      |         ^
```
